[project]
name = "food-map"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.104.0",
    "instaloader>=4.10.0",
    "pydantic>=2.0.0",
    "requests>=2.32.4",
    "uvicorn>=0.24.0",
]
